apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo
  namespace: todo-demo
  annotations:
    kubernetes.io/ingress.class: nginx

    # HTTP ile başlayıp doğrula, sonra TLS ekle
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

    # Basic protections / limits
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
    nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"

    # Timeouts
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: todo.example.com
      http:
        paths:
          # API
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: todo-api
                port:
                  number: 80

          # Health endpoints (UI health doğru çalışsın)
          - path: /healthz
            pathType: Prefix
            backend:
              service:
                name: todo-api
                port:
                  number: 80
          - path: /readyz
            pathType: Prefix
            backend:
              service:
                name: todo-api
                port:
                  number: 80

          # UI
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todo-web
                port:
                  number: 80